vaadin.launch-browser: true
spring:
  application:
    name: finance-cash-flow
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finance
    username: app_user
    password: mysecretpassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update